version: '3.8'

services:
  traefik:
    image: traefik:v2.3
    restart: always
    networks:
      - traefik-global-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./configuration/traefik/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  traefik-global-proxy:
    name: "traefik-global-proxy"

