[[tls.certificates]]
  certFile = "/ssl/domain-com.pem"
  keyFile = "/ssl/domain-com.pem"
  stores = ["default"]

[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "/ssl/domain-com.pem"
      keyFile  = "/ssl/domain-com.pem"
